language: node_js # 设置语言
node_js: stable # 设置相应版本
install:
    - npm install # 安装hexo及插件
script:
    - hexo clean # 清除
    - hexo g # 生成
after_script:
    - git config user.name "yeyaowei" # 修改name
    - git config user.email "yeyaowei@rhw-team.com" # 修改email
    - npm install -g hexo-cli
after_success:
    - git clone -b master git@github.com:yeyaowei/yeyaowei.github.io.git .deploy_git
    - cd .deploy_git
    - git checkout master
    - mv .git/ ../public/
    - cd ../public
    - git add .
    - git commit -m "Site updated: `date +"%Y-%m-%d %H:%M:%S"`"
branches:
    only:
        - source
