version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    filters:
      branches:
        only: source
    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "f8:7d:5d:c0:98:e5:3f:5e:35:16:b2:ef:77:3a:c0:eb"
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Clean
          command: yarn clean
      - run:
          name: Generate Public Files
          command: yarn build
      - run:
          name: Run Deploy Script
          command: bash .circleci/deploy.sh