version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    filters:
      branches:
        only: source
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ff:98:09:1d:21:0d:a8:c3:30:cf:2e:91:c7:03:4e:b1"
            - "97:08:a6:61:6f:19:c4:48:79:00:9e:32:b6:12:d2:c0"
      - checkout
      - run:
          name: Fetch Hexo Theme
          command: |
            git submodule init
            git submodule update
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Clean
          command: yarn clean
      - run:
          name: Generate Public Files
          command: yarn build
      - run:
          name: Run Deploy Script
          command: bash .circleci/deploy.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: source